version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directories:
      - "./axum-rest-api-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "./axum-rest-api-service"
    schedule:
      interval: "weekly"