[package]
name = "axum-rest-api-service"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "axum-rest-api-service"
path = "src/main.rs"

[dependencies]
axum = "0.8.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.44.1"
