name: cargo-build (axum-rest-api-service)

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
    paths:
      - 'axum-rest-api-service/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'axum-rest-api-service/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./axum-rest-api-service
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install and Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt,clippy

      - name: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-axum-rest-api-service-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: cargo-build
        run: cargo build

      - name: cargo-test
        run: cargo test

  dependabot:
    needs: [build]
    permissions: write-all
    uses: josephrodriguez/github-workflow/.github/workflows/dependabot-merge-pull-request.yaml@main
    secrets:
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}